import asyncio, os, sys, pathlib, hashlib
ROOT = str(pathlib.Path(__file__).resolve().parent.parent)
os.chdir(ROOT)
PAGE = pathlib.Path(ROOT, "index.html").as_uri()
from playwright.async_api import async_playwright
async def page(b, init="", vw=1440):
    pg = await b.new_page(viewport={"width": vw, "height": 900}, accept_downloads=True)
    errs = []; pg.on("pageerror", lambda e: errs.append(str(e)))
    await pg.expose_function("__md5", lambda arr: hashlib.md5(bytes(arr)).hexdigest())
    if init: await pg.add_init_script(init)
    await pg.add_init_script(path="test/mock_board.js")
    await pg.goto(PAGE)
    return pg, errs
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        # 1. auto start on a granted port + 80 MHz / 2048 defaults + wake lock
        pg, errs = await page(b)
        await pg.wait_for_timeout(3000)
        print("1 auto start:", await pg.inner_text("#chipText"), "|", await pg.inner_text("#tuneInfo"))
        # 2. play / stop
        await pg.click("#playBtn"); await pg.wait_for_timeout(800)
        f1 = await pg.inner_text("#stFrames"); await pg.wait_for_timeout(800); f2 = await pg.inner_text("#stFrames")
        cmds = await pg.evaluate("__board.cmds.slice(-2)")
        print("2 stopped:", await pg.inner_text("#chipText"), "frames frozen:", f1 == f2, "fw streaming:", await pg.evaluate("!!document"), cmds)
        await pg.click("#playBtn"); await pg.wait_for_timeout(1200)
        print("  restarted:", await pg.inner_text("#chipText"), "fps", await pg.inner_text("#stFps"))
        # 3. exports
        async with pg.expect_download() as d: await pg.click("#csvBtn")
        dl = await d.value; txt = open(await dl.path()).read().splitlines()
        print("3 snapshot:", dl.suggested_filename, len(txt) - 1, "rows,", txt[1])
        await pg.click("#expModeSeg button[data-v='avg']"); await pg.fill("#expN", "100"); await pg.press("#expN", "Tab")
        await pg.click("#expSpanSeg button[data-v='view']"); await pg.click("#zoomSeg button[data-v='4']")
        async with pg.expect_download(timeout=10000) as d: await pg.click("#csvBtn")
        dl = await d.value; txt = open(await dl.path()).read().splitlines()
        print("  average/visible:", dl.suggested_filename, len(txt) - 1, "rows,", txt[1], "...", txt[-1])
        await pg.fill("#logIv", "0.2"); await pg.press("#logIv", "Tab")
        await pg.click("#logBtn"); await pg.wait_for_timeout(1300)
        print("  log state:", await pg.inner_text("#logState"))
        async with pg.expect_download() as d: await pg.click("#logBtn")
        dl = await d.value; txt = open(await dl.path()).read().splitlines()
        print("  log file:", dl.suggested_filename, len(txt) - 1, "rows x", len(txt[0].split(",")) - 1, "bins; header", txt[0][:60])
        async with pg.expect_download() as d: await pg.click("#debugBtn")
        dl = await d.value; txt = open(await dl.path()).read().splitlines()
        print("  debug report:", dl.suggested_filename, len(txt), "lines;", txt[1]); print("   ", txt[5][:110])
        print("  errors:", errs); await pg.close()
        # 4. out-of-range saved frequency (the t.janos case)
        pg, errs = await page(b, 'localStorage.setItem("z2-web-sdr", JSON.stringify({freqHz: 144e6}));')
        await pg.wait_for_timeout(700)
        print("4 toast:", await pg.inner_text("#toast"), "| readout:", await pg.input_value("#freqIn"))
        await pg.close()
        # 5. wrong port (USB-UART bridge)
        pg, errs = await page(b, 'window.__vid = 0x1a86;')
        await pg.evaluate("""() => { const p = navigator.serial; const orig = p.requestPort; }""")
        await pg.close()
        # 6. phone: sheet + scrim close
        pg, errs = await page(b, "", 400)
        await pg.wait_for_timeout(2500)
        await pg.click("#rackBtn"); await pg.wait_for_timeout(400)
        open1 = await pg.evaluate("document.getElementById('rack').classList.contains('open')")
        await pg.mouse.click(200, 120); await pg.wait_for_timeout(400)
        open2 = await pg.evaluate("document.getElementById('rack').classList.contains('open')")
        print("6 sheet open:", open1, "-> after outside tap:", open2)
        await pg.screenshot(path="test/phone_live.png")
        print("  errors:", errs)
        await b.close()
        if errs: sys.exit(1)
asyncio.run(main())
