import asyncio, os, sys, pathlib
ROOT = str(pathlib.Path(__file__).resolve().parent.parent)
os.chdir(ROOT)
PAGE = pathlib.Path(ROOT, "index.html").as_uri()
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        pg = await b.new_page(viewport={"width": 1440, "height": 860})
        errs = []
        pg.on("pageerror", lambda e: errs.append(str(e)))
        await pg.add_init_script(path="test/mock_serial.js")
        await pg.goto(PAGE)
        await pg.wait_for_timeout(500)
        await pg.click("#connectBtn")
        await pg.wait_for_timeout(2500)
        print("chip:", await pg.inner_text("#chipText"), "| fw:", await pg.inner_text("#fwInfo"))
        print("tune:", await pg.inner_text("#tuneInfo"))
        print("stats fps/frames/lost/crc:", [await pg.inner_text(s) for s in ["#stFps", "#stFrames", "#stLost", "#stCrc"]])
        await pg.click("#peakFind"); await pg.wait_for_timeout(200)
        print("marker:", await pg.inner_text("#markerRead"))
        # retune 3 MHz up by keyboard, then switch to 80 MHz / 2048
        await pg.mouse.click(5, 300)
        for _ in range(3): await pg.keyboard.press("ArrowRight")
        await pg.click("#spanSeg button[data-v='80000000']")
        await pg.wait_for_timeout(1500)
        await pg.click("#binsSeg button[data-v='2048']")
        await pg.wait_for_timeout(2000)
        print("tune:", await pg.inner_text("#tuneInfo"))
        await pg.click("#peakFind"); await pg.wait_for_timeout(200)
        print("marker:", await pg.inner_text("#markerRead"))
        cmds = await pg.evaluate("window.__fw.cmds")
        print("fw saw:", [c for c in cmds if c.startswith(("FREQ","FOFS","SPEC "))])
        print("stats:", [await pg.inner_text(s) for s in ["#stFps", "#stFrames", "#stLost", "#stCrc", "#stRestarts"]])
        await pg.screenshot(path="test/live.png")
        await pg.click("#connectBtn"); await pg.wait_for_timeout(1500)
        cmds = await pg.evaluate("window.__fw.cmds")
        print("after disconnect, last cmds:", cmds[-3:], "| chip:", await pg.inner_text("#chipText"))
        print("errors:", errs)
        await b.close()
        if errs: sys.exit(1)
asyncio.run(main())
